# install loki docker plugin first:
# docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
version: "3"
services:
  tempo:
    image: grafana/tempo:2.0.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"  # otlp grpc
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.7.4
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./etc/loki.yaml:/etc/loki/config.yaml

  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./etc/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=system
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=false
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
