apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: golang-http-service
build:
  artifacts:
    - image: slamdev/golang-http-service
      hooks:
        before:
          - command: [ make, assemble-linux ]
            os: [ darwin, linux ]
      custom:
        buildCommand: docker buildx build --tag=$IMAGE --push --platform=$PLATFORMS --quiet .
        dependencies:
          paths:
            - "api/**"
            - "configs/**"
            - "pkg/**"
            - "go.mod"
            - "go.sum"
            - "main.go"
            - "Dockerfile"
            - "Makefile"
  tagPolicy:
    inputDigest: { }
  platforms: [ linux/amd64 ]
deploy:
  helm:
    releases:
      - name: golang-http-service
        chartPath: deployments/helm-chart
        valuesFiles: [ ]
        setValueTemplates:
          image.repository: '{{ .IMAGE_REPO_slamdev_golang_http_service }}'
          image.tag: '{{ .IMAGE_TAG_slamdev_golang_http_service }}@{{ .IMAGE_DIGEST_slamdev_golang_http_service }}'
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
profiles:
  - name: dev
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - deployments/environments/values.dev.yaml
  - name: prod
    patches:
      - op: add
        path: /manifests/helm/releases/0/valuesFiles
        value:
          - deployments/environments/values.prod.yaml
