name: Run build
on:
  pull_request:
    paths-ignore:
      - 'deployments/**'
  workflow_dispatch: { }
defaults: { run: { shell: bash } }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Prepare
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh 
          curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh 
          go mod download
      - name: Build app
        run: make build
      - name: Run e2e tests
        run: |
          make run &
          make e2e-tests
