name: Run deploy
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'tests/**'
      - 'deployments/observability-stack/**'
      - 'README.md'
  workflow_dispatch: { }
defaults: { run: { shell: bash } }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Prepare
        run: |
          curl -sLo skaffold https://storage.googleapis.com/skaffold/releases/v2.2.0/skaffold-linux-amd64
          chmod +x skaffold && sudo mv skaffold /usr/local/bin
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Deploy
        run: skaffold run -pdev
